import { Message } from "ai";
import { BLUEPRINT_DESC } from "./blueprint-desc";

// export const EditPageFunction = {
//   name: "editPage",
//   description:
//     "Edit various Blueprints on the page to best satisfy the user's request",
//   parameters: zodToJsonSchema(PageEditSchema),
// };

export function createEditBlueprintPrompt(
  pageTree: any,
  messages: Array<Message>,
) {
  const userRequest = messages[messages.length - 1].content;

  console.log("Starting to create context");

  // ## Library API
  // You will have access to the following Library component packages if you need them:
  // ${formatCollections(collections)}

  const context: Array<{
    role: "system" | "user" | "assistant";
    content: string;
  }> = [
    {
      role: `system`,
      content: `
      # BLUEPRINT WRITE STEP
      Your task is to take a user's request for a webpage as well as a wireframe designed in the WIREFRAME DESIGN STEP and fill out the Blueprint for the webpage.
      You will create a series of edits to nodes in the existing Blueprint in accordance with a user's request.

      Here is the Blueprint API:
      ${BLUEPRINT_DESC}

      ## Current version of the Blueprint (note that it has been annotated with paths for each node, whereas what you output does not need paths):
      ${JSON.stringify(pageTree, null, 2)}

      ### Final notes
      These webpages are supposed to be fun. They are generated by users -- normal people -- to express themselves or something they're interested in. They don't have to have footers or other conventional web design things. In fact, the more unconventional the design the better (though the user gets to decide this ultimately). 
      
      # WARNING
      If you do not use the editVariousNodes() tool, it will cause a runtime error on the user's end. Do not return any messages, do not say anything to the user. Only use the editVariousNodes() functions.
      `,
    },
    {
      role: "user",
      content: userRequest,
    },
  ];
  return context;
}
